# Polynomial Regression

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Importing the dataset

In [5]:
dataset = pd.read_csv('/content/drive/MyDrive/Machine Learning - Udemy/Machine Learning A-Z (Model Selection)/Regression/Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Polynomial Regression model on the Training set

In [11]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

[[1.00e+00 1.12e+01 4.31e+01 ... 6.77e+09 5.39e+08 4.28e+07]
 [1.00e+00 1.37e+01 5.43e+01 ... 5.87e+09 4.36e+08 3.24e+07]
 [1.00e+00 3.28e+01 7.80e+01 ... 2.16e+09 9.75e+07 4.40e+06]
 ...
 [1.00e+00 1.68e+01 3.85e+01 ... 5.87e+09 4.33e+08 3.20e+07]
 [1.00e+00 1.28e+01 4.12e+01 ... 7.77e+09 6.55e+08 5.52e+07]
 [1.00e+00 3.23e+01 6.79e+01 ... 1.46e+09 5.49e+07 2.07e+06]]


## Predicting the Test set results

In [8]:
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[433.94 431.23]
 [457.9  460.01]
 [460.52 461.14]
 ...
 [469.53 473.26]
 [438.27 438.  ]
 [461.66 463.28]]


## Evaluating the Model Performance

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9458192606428147